var namespacepip_1_1__vendor =
[
    [ "cachecontrol", "namespacepip_1_1__vendor_1_1cachecontrol.html", "namespacepip_1_1__vendor_1_1cachecontrol" ],
    [ "certifi", "namespacepip_1_1__vendor_1_1certifi.html", "namespacepip_1_1__vendor_1_1certifi" ],
    [ "chardet", "namespacepip_1_1__vendor_1_1chardet.html", "namespacepip_1_1__vendor_1_1chardet" ],
    [ "colorama", "namespacepip_1_1__vendor_1_1colorama.html", "namespacepip_1_1__vendor_1_1colorama" ],
    [ "distlib", "namespacepip_1_1__vendor_1_1distlib.html", "namespacepip_1_1__vendor_1_1distlib" ],
    [ "distro", "namespacepip_1_1__vendor_1_1distro.html", "namespacepip_1_1__vendor_1_1distro" ],
    [ "idna", "namespacepip_1_1__vendor_1_1idna.html", "namespacepip_1_1__vendor_1_1idna" ],
    [ "msgpack", "namespacepip_1_1__vendor_1_1msgpack.html", "namespacepip_1_1__vendor_1_1msgpack" ],
    [ "packaging", "namespacepip_1_1__vendor_1_1packaging.html", "namespacepip_1_1__vendor_1_1packaging" ],
    [ "pkg_resources", "namespacepip_1_1__vendor_1_1pkg__resources.html", "namespacepip_1_1__vendor_1_1pkg__resources" ],
    [ "platformdirs", "namespacepip_1_1__vendor_1_1platformdirs.html", "namespacepip_1_1__vendor_1_1platformdirs" ],
    [ "pygments", "namespacepip_1_1__vendor_1_1pygments.html", "namespacepip_1_1__vendor_1_1pygments" ],
    [ "pyparsing", "namespacepip_1_1__vendor_1_1pyparsing.html", "namespacepip_1_1__vendor_1_1pyparsing" ],
    [ "pyproject_hooks", "namespacepip_1_1__vendor_1_1pyproject__hooks.html", "namespacepip_1_1__vendor_1_1pyproject__hooks" ],
    [ "requests", "namespacepip_1_1__vendor_1_1requests.html", "namespacepip_1_1__vendor_1_1requests" ],
    [ "resolvelib", "namespacepip_1_1__vendor_1_1resolvelib.html", "namespacepip_1_1__vendor_1_1resolvelib" ],
    [ "rich", "namespacepip_1_1__vendor_1_1rich.html", "namespacepip_1_1__vendor_1_1rich" ],
    [ "six", "namespacepip_1_1__vendor_1_1six.html", "namespacepip_1_1__vendor_1_1six" ],
    [ "tenacity", "namespacepip_1_1__vendor_1_1tenacity.html", "namespacepip_1_1__vendor_1_1tenacity" ],
    [ "tomli", "namespacepip_1_1__vendor_1_1tomli.html", "namespacepip_1_1__vendor_1_1tomli" ],
    [ "typing_extensions", "namespacepip_1_1__vendor_1_1typing__extensions.html", "namespacepip_1_1__vendor_1_1typing__extensions" ],
    [ "urllib3", "namespacepip_1_1__vendor_1_1urllib3.html", "namespacepip_1_1__vendor_1_1urllib3" ],
    [ "webencodings", "namespacepip_1_1__vendor_1_1webencodings.html", "namespacepip_1_1__vendor_1_1webencodings" ],
    [ "vendored", "namespacepip_1_1__vendor.html#a5b4bb9879e43bddcc9264ac473350d20", null ],
    [ "DEBUNDLED", "namespacepip_1_1__vendor.html#acd8eb8d592017eeb72e2ed3b9579e333", null ],
    [ "WHEEL_DIR", "namespacepip_1_1__vendor.html#abd21f09daa1bca38f87061036109fd3b", null ]
];