var setuptools_2__vendor_2importlib__resources_2__adapters_8py =
[
    [ "SpecLoaderAdapter", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_spec_loader_adapter.html", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_spec_loader_adapter" ],
    [ "TraversableResourcesLoader", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_traversable_resources_loader.html", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_traversable_resources_loader" ],
    [ "CompatibilityFiles", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files.html", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files" ],
    [ "CompatibilityFiles.SpecPath", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files_1_1_spec_path.html", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files_1_1_spec_path" ],
    [ "CompatibilityFiles.ChildPath", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files_1_1_child_path.html", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files_1_1_child_path" ],
    [ "CompatibilityFiles.OrphanPath", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files_1_1_orphan_path.html", "classsetuptools_1_1__vendor_1_1importlib__resources_1_1__adapters_1_1_compatibility_files_1_1_orphan_path" ],
    [ "_io_wrapper", "setuptools_2__vendor_2importlib__resources_2__adapters_8py.html#a0a3c5d4c2c4623b44eed341fc529f2e0", null ],
    [ "wrap_spec", "setuptools_2__vendor_2importlib__resources_2__adapters_8py.html#aaf332a4769b1ef1e7fee7b48daa20675", null ]
];