#include <stdint.h>
#include <esp_https_server.h>

// FIX: This is using certificates generated by Espressif for a demo,
// becuase I haven't figured out the exact magic incantation to create
// ones that MBEDTLS likes, and the instructions that came with those
// certificates don't work either.

// This is a self-signed certificate authority, and a device certificate
// signed by it. I'll keep the private key for the CA safe, but the device
// certificate is not secure because the private key is public  knowledge
// right in this source file. This is enough to get a LetsEncrypt certificate
// for a public IP, and we might also work out a way to issue device users
// individual certificates which stay private.

// FIX: Might not need the newline character here.
// Test that after this works.
#if 0
static const uint8_t	ca_public_pem[] = "\
-----BEGIN CERTIFICATE-----\n\
MIIGMzCCBBugAwIBAgIUW0+3c6aav+LS1D3YDG0r4V27zegwDQYJKoZIhvcNAQEL\n\
BQAwgagxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMREwDwYDVQQH\n\
DAhCZXJrZWxleTENMAsGA1UECgwESzZCUDElMCMGA1UECwwcSFQgQ3J5cHRvZ3Jh\n\
cGhpYyBDZXJ0aWZpY2F0ZTEaMBgGA1UEAwwRQnJ1Y2UgUGVyZW5zIEs2QlAxHzAd\n\
BgkqhkiG9w0BCQEWEGJydWNlQHBlcmVucy5jb20wHhcNMjUwMjE4MDIyMjM5WhcN\n\
NDAwMjE1MDIyMjM5WjCBqDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3Ju\n\
aWExETAPBgNVBAcMCEJlcmtlbGV5MQ0wCwYDVQQKDARLNkJQMSUwIwYDVQQLDBxI\n\
VCBDcnlwdG9ncmFwaGljIENlcnRpZmljYXRlMRowGAYDVQQDDBFCcnVjZSBQZXJl\n\
bnMgSzZCUDEfMB0GCSqGSIb3DQEJARYQYnJ1Y2VAcGVyZW5zLmNvbTCCAiIwDQYJ\n\
KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKv4eITpnwfxk/uNhx4TQ63k+nZ3tEKJ\n\
5mkLRugoL/3SsTK1Xe6C270pWVtrC8wipoVFKs1wfrSujNIdEx4Y+1mArUJ8darL\n\
NUb6XZ73Vxa0lmBTAFdvGTd+3AHiTjFMZOrKudxRJos6Eb74Oby6PBG/olLU2hkT\n\
PahxzeGkFD+Qt2DSZPneLlT46oNvb7T2x8pDBhM6HWYLfc9+vXIzW9rw5fSzNDU9\n\
UIH6Ovuc2rZu/za6HBOt95APmqJdnhH0Qv8dnpo6q4Q8Z+moE9Rrzu16UtJAmITL\n\
vgkWOFey5XBj8K43u2XsnVaMDY6lhtNYZdPBGkaahk+X+u6yk6gzq/jfzkEpDdYC\n\
+ZpqwOG2SaCsD7O2+lnQ1b1MQnxrtdpvDhQ39S63iPNATOszx2hIeVw2I78zTwvV\n\
CSBGSasxMZZKqtoyM6LSrMCNSP2AducDpVghdCJOJh0+LmMPpBlFrg9Wn1YJf+xk\n\
ZWC6BcXLd30dYn4ODLK0ur94fXWYjEGHa+4FJNCA6X8++iQKuYpOiPhvfIZe5wB0\n\
g0K00YtCejK/nuxMtI2WfnZ1fPFRwDeMT4cpMxeaxsWwui57eAZ5B2TpsO2lg6pS\n\
O3CN0HvTXSRFdXhyLMNBFn7eFFL3KSyw2YnvKuc54UALX2AdoEQGzCdRn42iFDXw\n\
9eOQ5FTvaf/pAgMBAAGjUzBRMB0GA1UdDgQWBBTkcw7207jLJjh9aTUgazQKcvy2\n\
djAfBgNVHSMEGDAWgBTkcw7207jLJjh9aTUgazQKcvy2djAPBgNVHRMBAf8EBTAD\n\
AQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCoiyy73XOrn2aM/ormyswi3o571AvD3QfA\n\
FpGNbuXfxVcndaCaYd2JxMUj+3//r4jyUOqihvmqKcG2L0QuzazKd06W9mtBD9Or\n\
tLtSU5NmW7HizBonBPpZEU4RQ0umAhfMI0C8LlLhxRUY7nLmWksi3TRT2w+4lLsd\n\
Kd5ZivrA57SqXNs21hFw7M+KtD1VkCjlAaMjbXebutQoGxOYpVNrL5LwlYSQ1qYp\n\
isg/MkdaWoSsupgl/bGgcbCe0mjjLy+ARhA78KarEVvpmZWr2thGpSxZSHdepugl\n\
c3vhOUbvZQLEXtU+DbpSiQNkxw+b1WsAJwCwu3ex8yCOI6FjKSuhigE0ZNJLqGde\n\
oiDQj26oF2LpABWMSA9Wja1U7zuK7PVIbWfhr1zHX0C/XnTlql2wLqVdeGJoMpXO\n\
PCDRMup7IN0LsGM6uf1w+9uRaDIpwZHwuq66QU1nTr944IRmVxlC1N4i3dWIg3vW\n\
JZRovi2H90QCl/7zCTttkTd7NP7t0py810YQMCLUTfRc1RDCHqarRZFyUjygncTs\n\
4HTJ+szwuajj2b3M4pFhA7ab6VWn+MQHnJo9KDmyvYTCcXMV4G9j8+7hQRfgAmIw\n\
NVo8kVrGNXPO7QfTiYfPlEScQBjM7kjT5Olm4S5Vb5w25YyS91GTyI1m1+2LI3kP\n\
dMz+MJYNPA==\n\
-----END CERTIFICATE-----\n";
#endif

static const uint8_t	public_pem[] = "\
-----BEGIN CERTIFICATE-----\n\
MIIDKzCCAhOgAwIBAgIUBxM3WJf2bP12kAfqhmhhjZWv0ukwDQYJKoZIhvcNAQEL\n\
BQAwJTEjMCEGA1UEAwwaRVNQMzIgSFRUUFMgc2VydmVyIGV4YW1wbGUwHhcNMTgx\n\
MDE3MTEzMjU3WhcNMjgxMDE0MTEzMjU3WjAlMSMwIQYDVQQDDBpFU1AzMiBIVFRQ\n\
UyBzZXJ2ZXIgZXhhbXBsZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\n\
ALBint6nP77RCQcmKgwPtTsGK0uClxg+LwKJ3WXuye3oqnnjqJCwMEneXzGdG09T\n\
sA0SyNPwrEgebLCH80an3gWU4pHDdqGHfJQa2jBL290e/5L5MB+6PTs2NKcojK/k\n\
qcZkn58MWXhDW1NpAnJtjVniK2Ksvr/YIYSbyD+JiEs0MGxEx+kOl9d7hRHJaIzd\n\
GF/vO2pl295v1qXekAlkgNMtYIVAjUy9CMpqaQBCQRL+BmPSJRkXBsYk8GPnieS4\n\
sUsp53DsNvCCtWDT6fd9D1v+BB6nDk/FCPKhtjYOwOAZlX4wWNSZpRNr5dfrxKsb\n\
jAn4PCuR2akdF4G8WLUeDWECAwEAAaNTMFEwHQYDVR0OBBYEFMnmdJKOEepXrHI/\n\
ivM6mVqJgAX8MB8GA1UdIwQYMBaAFMnmdJKOEepXrHI/ivM6mVqJgAX8MA8GA1Ud\n\
EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBADiXIGEkSsN0SLSfCF1VNWO3\n\
emBurfOcDq4EGEaxRKAU0814VEmU87btIDx80+z5Dbf+GGHCPrY7odIkxGNn0DJY\n\
W1WcF+DOcbiWoUN6DTkAML0SMnp8aGj9ffx3x+qoggT+vGdWVVA4pgwqZT7Ybntx\n\
bkzcNFW0sqmCv4IN1t4w6L0A87ZwsNwVpre/j6uyBw7s8YoJHDLRFT6g7qgn0tcN\n\
ZufhNISvgWCVJQy/SZjNBHSpnIdCUSJAeTY2mkM4sGxY0Widk8LnjydxZUSxC3Nl\n\
hb6pnMh3jRq4h0+5CZielA4/a+TdrNPv/qok67ot/XJdY3qHCCd8O2b14OVq9jo=\n\
-----END CERTIFICATE-----\n";

static const uint8_t	private_pem[] = "\
-----BEGIN PRIVATE KEY-----\n\
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwYp7epz++0QkH\n\
JioMD7U7BitLgpcYPi8Cid1l7snt6Kp546iQsDBJ3l8xnRtPU7ANEsjT8KxIHmyw\n\
h/NGp94FlOKRw3ahh3yUGtowS9vdHv+S+TAfuj07NjSnKIyv5KnGZJ+fDFl4Q1tT\n\
aQJybY1Z4itirL6/2CGEm8g/iYhLNDBsRMfpDpfXe4URyWiM3Rhf7ztqZdveb9al\n\
3pAJZIDTLWCFQI1MvQjKamkAQkES/gZj0iUZFwbGJPBj54nkuLFLKedw7DbwgrVg\n\
0+n3fQ9b/gQepw5PxQjyobY2DsDgGZV+MFjUmaUTa+XX68SrG4wJ+DwrkdmpHReB\n\
vFi1Hg1hAgMBAAECggEAaTCnZkl/7qBjLexIryC/CBBJyaJ70W1kQ7NMYfniWwui\n\
f0aRxJgOdD81rjTvkINsPp+xPRQO6oOadjzdjImYEuQTqrJTEUnntbu924eh+2D9\n\
Mf2CAanj0mglRnscS9mmljZ0KzoGMX6Z/EhnuS40WiJTlWlH6MlQU/FDnwC6U34y\n\
JKy6/jGryfsx+kGU/NRvKSru6JYJWt5v7sOrymHWD62IT59h3blOiP8GMtYKeQlX\n\
49om9Mo1VTIFASY3lrxmexbY+6FG8YO+tfIe0tTAiGrkb9Pz6tYbaj9FjEWOv4Vc\n\
+3VMBUVdGJjgqvE8fx+/+mHo4Rg69BUPfPSrpEg7sQKBgQDlL85G04VZgrNZgOx6\n\
pTlCCl/NkfNb1OYa0BELqWINoWaWQHnm6lX8YjrUjwRpBF5s7mFhguFjUjp/NW6D\n\
0EEg5BmO0ePJ3dLKSeOA7gMo7y7kAcD/YGToqAaGljkBI+IAWK5Su5yldrECTQKG\n\
YnMKyQ1MWUfCYEwHtPvFvE5aPwKBgQDFBWXekpxHIvt/B41Cl/TftAzE7/f58JjV\n\
MFo/JCh9TDcH6N5TMTRS1/iQrv5M6kJSSrHnq8pqDXOwfHLwxetpk9tr937VRzoL\n\
CuG1Ar7c1AO6ujNnAEmUVC2DppL/ck5mRPWK/kgLwZSaNcZf8sydRgphsW1ogJin\n\
7g0nGbFwXwKBgQCPoZY07Pr1TeP4g8OwWTu5F6dSvdU2CAbtZthH5q98u1n/cAj1\n\
noak1Srpa3foGMTUn9CHu+5kwHPIpUPNeAZZBpq91uxa5pnkDMp3UrLIRJ2uZyr8\n\
4PxcknEEh8DR5hsM/IbDcrCJQglM19ZtQeW3LKkY4BsIxjDf45ymH407IQKBgE/g\n\
Ul6cPfOxQRlNLH4VMVgInSyyxWx1mODFy7DRrgCuh5kTVh+QUVBM8x9lcwAn8V9/\n\
nQT55wR8E603pznqY/jX0xvAqZE6YVPcw4kpZcwNwL1RhEl8GliikBlRzUL3SsW3\n\
q30AfqEViHPE3XpE66PPo6Hb1ymJCVr77iUuC3wtAoGBAIBrOGunv1qZMfqmwAY2\n\
lxlzRgxgSiaev0lTNxDzZkmU/u3dgdTwJ5DDANqPwJc6b8SGYTp9rQ0mbgVHnhIB\n\
jcJQBQkTfq6Z0H6OoTVi7dPs3ibQJFrtkoyvYAbyk36quBmNRjVh6rc8468bhXYr\n\
v/t+MeGJP/0Zw8v/X2CFll96\n\
-----END PRIVATE KEY-----\n";

// Call this on a structure that has already been initialized with
// HTTPD_SSL_CONFIG_DEFAULT().
void
gm_self_signed_ssl_certificates(struct httpd_ssl_config * c)
{
  c->servercert = public_pem;
  c->servercert_len = sizeof(public_pem);
  // c->cacert_pem = ca_public_pem;
  // c->cacert_len = sizeof(ca_public_pem);
  c->prvtkey_pem = private_pem;
  c->prvtkey_len = sizeof(private_pem);
}
